spring:
  application:
    name: attribute-converter-18-05-2024
  datasource:
    url: jdbc:postgresql://localhost:5431/postgres
    username: postgres
    password: "010104"
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true

springdoc:
  swagger-ui:
    path: /api

server:
  port: 8080  # Add your desired port number here
